server:
  port: 8091
  servlet:
    multipart:
      file-size-threshold: 1MB #파일이 메모리에 기록되는 임계값 (default: 0B)
      locaion: C:/imgTemp #업로드된 파일의 임시 저장 공간
      max-file-size: 100MB #파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB #요청의 최대 사이즈 (default: 10MB)
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools: #서버 자동 시작
    livereload:
      enabled: true
      
  datasource: #마이베티스 dataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/kfood?characterEncoding=utf-8
    username: root
    password: root1234
    
mybatis: #mybatis에서 package명 생략가능하게 만드는 기능 spring 프로젝트 mapper에서 썻던 resultType의 vo패키지를 선택할 때 쓰는 것들 생략
  type-aliases-package: com.campus.myapp.vo
  mapper-locations: mapper/*Mapper.xml
  
  